{% set name = "pyramid_log" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f31d8e779d989a4d2a519a433f1d49a197def4ea2d2f31637ace88f02475712

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyramid
    # actually required by pyramid on 2.7 -- but not there in the main package
    - repoze.lru

test:
  imports:
    - pyramid_log

about:
  home: https://pypi.org/project/pyramid-log/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python logging formatter for Pyramid
  description: |
    The pyramid_log distribution includes a Python logging formatter which
    makes Pyramid request attributes available for use in its format string.
    Specifically, pyramid_log.Formatter is special...
  dev_url: https://github.com/dairiki/pyramid_log/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
