{% set name = "pyramid_log" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3f28ca34e8d34d282eb5897689cd9cfc3ba20bd2a847f1b807df93ff5937b09

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python>=3.6
    - pip
  run:
    - python>=3.6
    - pyramid
    # actually required by pyramid on 2.7 -- but not there in the main package
    - repoze.lru

test:
  imports:
    - pyramid_log

about:
  home: https://pypi.org/project/pyramid-log/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Python logging formatter for Pyramid
  description: |
    The pyramid_log distribution includes a Python logging formatter which
    makes Pyramid request attributes available for use in its format string.
    Specifically, pyramid_log.Formatter is special...
  dev_url: https://github.com/dairiki/pyramid_log/

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
